name: domain
description: "Domain layer is high level module and package for flutter_bloc_architecture (defines entities, use-cases, and repositories interfaces)."
version: 0.0.1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
resolution: workspace

environment:
  sdk: ^3.11.5
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: any
  injectable: any
  twofold: any

dev_dependencies:
  build_runner: any
  flutter_lints: any
  flutter_test:
    sdk: flutter

  injectable_generator: any
  mockito: ^5.6.4

flutter:

  uses-material-design: true