name: domain
description: "A new Flutter project."
version: 0.0.1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:

  dartz:
    git:
      url: https://github.com/rahul-gola/dartz.git

  flutter:
    sdk: flutter

  get_it: ^8.2.0
  injectable: ^2.5.1
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.7.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  injectable_generator: ^2.8.1
  json_serializable: ^6.11.1
