name: domain
description: "Domain layer package for flutter_bloc_architecture (defines entities, use-cases, and repositories interfaces)."
version: 0.0.1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:

  dart_mappable: ^4.6.1
  dartz:
    git:
      url: https://github.com/rahul-gola/dartz.git

  flutter:
    sdk: flutter

  get_it: ^8.2.0
  injectable: ^2.5.2

dev_dependencies:
  build_runner: ^2.10.0
  dart_mappable_builder: ^4.6.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

  injectable_generator: ^2.9.0
