name: CI Build and Release

on:
  push:
    branches:
      - main
      - master
      - custom_either_package
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Fetch dependencies
        run: flutter pub get

#      - name: Analyze
#        run: flutter analyze

#      - name: Run tests
#        run: flutter test --no-pub

      - name: Build APK (release)
        run: flutter build apk --release --build-name 1.0.${{ github.run_number }} --build-number ${{ github.run_number }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk-${{ github.run_number }}
          path: build/app/outputs/flutter-apk/app-release.apk

  release:
    needs: build-android
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: build-${{ github.run_number }}
          release_name: Build #${{ github.run_number }}
          draft: false
          prerelease: true

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-release-apk-${{ github.run_number }}
          path: artifacts

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/app-release.apk
          asset_name: app-release-${{ github.run_number }}.apk
          asset_content_type: application/vnd.android.package-archive
